### ISSUE TITLE
Failed to link to module 'rlm_rest'

### ISSUE THREAD

**Issue by ramwolken9** [fgsants/RESTServer-FreeRADIUS#1]
Hey,
I'm trying to setup my server as mentioned in your repo README.. But struck with the following error..
Could you please look into this and help to fix this
/usr/local/etc/raddb/mods-enabled/rest[1]: Failed to link to module 'rlm_rest': /usr/local/lib/rlm_rest.so: cannot open shared object file: No such file or directory

**Comment by fgsants** [comment]
This error means that the rlm_rest module isn't present. Probably some build dependendies are missing for the module. Please check if you have "libjson-c-dev" installed. If not, install it with "apt-get install libjson-c-dev", then rebuild freeradius and try again.

**Comment by ramwolken9** [comment]
I did that.. But no use.. Same error repeated

**Comment by ramwolken9** [comment]
Is  there any way to install it manually ?

**Comment by ramwolken9** [comment]
It worked... Thank you!
I used this doc for freeRadius installation 
http://wiki.freeradius.org/building/Debian%20and%20Ubuntu
