### ISSUE TITLE
Getting 'npm run start' errors, please specify npm/node versions and how to install

### ISSUE THREAD

**Issue by umesh3034** [fgsants/RESTServer-FreeRADIUS#2]
eumesbs@elxa4r7r022:/home/opensource/REST-API-FreeRADIUS$ npm run start

> rest-api-freeradius@1.0.0 start /home/opensource/REST-API-FreeRADIUS
> nodemon server.js

/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/index.js:2
const spawn = require('child_process').spawn;
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodemon/bin/nodemon.js:15:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
eumesbs@elxa4r7r022:/home/opensource/REST-API-FreeRADIUS$ npm -v
1.3.10
eumesbs@elxa4r7r022:/home/opensource/REST-API-FreeRADIUS$ node -v
v0.10.25
eumesbs@elxa4r7r022:/home/opensource/REST-API-FreeRADIUS$ dpkg -l | grep nodejs
ii  nodejs                                                0.10.25~dfsg2-2ubuntu1                                            amd64        evented I/O for V8 javascript
ii  nodejs-dev                                            0.10.25~dfsg2-2ubuntu1                                            amd64        evented I/O for V8 javascript (development files)
ii  nodejs-legacy                                         0.10.25~dfsg2-2ubuntu1                                            all          evented I/O for V8 javascript (legacy symlink)
eumesbs@elxa4r7r022:/home/opensource/REST-API-FreeRADIUS$

**Comment by fgsants** [comment]
Hi @umesh3034 those where the versions I used during dev. But any versions higher should also work:

- node: v7.2.0
- npm: 3.10.9
