### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by im2kl** [fgsants/RESTServer-FreeRADIUS#3]
(node:32340) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:32340) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/root/freeradius-server/REST-API-FreeRADIUS/node_modules/mongodb-core/lib/topologies/server.js:562:11)

Must edit config.js to include port.
must add above to the connection string.  { useNewUrlParser: true }

**Comment by fgsants** [comment]
Thank you for pointing out. Fixed with merged pull request #4
